<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/gregoryerrl/Projects/web/cainta-motors/static/gltf/honda_city_rs/scene.gltf --output /Users/gregoryerrl/Projects/web/cainta-motors/src/lib/components/three/ --name HondaCityGenerated
Author: 3DHA (https://sketchfab.com/howtodrwcars)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/honda-city-rs-1d5a7dc0b3674e779bf88afdd2f4fd46
Title: Honda City RS
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf(
    '//Users/gregoryerrl/Projects/web/cainta-motors/static/gltf/honda_city_rs/scene.gltf'
  )
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, -0.13, 0]}
      scale={0}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_7.geometry}
        material={gltf.materials.material}
        position={[-10.27, 88.35, 24.95]}
        rotation={[2.28, -0.02, -0.03]}
        scale={[269.4, 29.38, 11.51]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_10.geometry}
        material={gltf.materials.material_1}
        position={[-78.89, -99.22, 37.32]}
        rotation={[2.41, 1.54, -2.22]}
        scale={[21.43, 22.79, 0.82]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_13.geometry}
        material={gltf.materials.material_2}
        position={[-28.62, -97.39, 36.86]}
        rotation={[2.41, 1.54, -2.22]}
        scale={[21.43, 22.79, 0.82]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_16.geometry}
        material={gltf.materials.material_3}
        position={[66.98, -98.36, 35.15]}
        rotation={[2.41, 1.54, -2.22]}
        scale={[21.43, 22.79, 0.82]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_19.geometry}
        material={gltf.materials.material_4}
        position={[27.03, -97.7, 35.88]}
        rotation={[2.41, 1.54, -2.22]}
        scale={[21.43, 22.79, 0.82]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_22.geometry}
        material={gltf.materials.material_5}
        position={[-122.95, -99.15, 38.01]}
        rotation={[2.41, 1.54, -2.22]}
        scale={[21.43, 22.79, 0.82]}
      />
      <T.Group
        position={[-19.2, 25.08, 8.24]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 1.55, 0]}
          scale={1.34}
        >
          <T.Group rotation={[-Math.PI, -1.54, -Math.PI]}>
            <T.Mesh
              geometry={gltf.nodes.Object_30.geometry}
              material={gltf.materials.material_6}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_35.geometry}
              material={gltf.materials.material_7}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_40.geometry}
              material={gltf.materials.material_8}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_45.geometry}
              material={gltf.materials.material_9}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_50.geometry}
              material={gltf.materials.material_10}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_55.geometry}
              material={gltf.materials.material_11}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_60.geometry}
              material={gltf.materials.material_12}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_65.geometry}
              material={gltf.materials.material_13}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_70.geometry}
              material={gltf.materials.material_14}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_75.geometry}
              material={gltf.materials.material_15}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_80.geometry}
              material={gltf.materials.material_16}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_85.geometry}
              material={gltf.materials.material_17}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_90.geometry}
              material={gltf.materials.material_18}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_95.geometry}
              material={gltf.materials.material_19}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_100.geometry}
              material={gltf.materials.material_20}
              position={[0, -224.02, 598.61]}
              scale={110}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[-176.12, -109.46, 854.55]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, -0.07, 0]}
          scale={[-0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_106.geometry}
              material={gltf.materials.material_21}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_109.geometry}
              material={gltf.materials.material_22}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_112.geometry}
              material={gltf.materials.material_23}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[73.43, -18.98, 1089.2]}
        rotation={[0.13, 0.32, -0.03]}
        scale={[0.2, 0.11, 0.11]}
      >
        <T.Mesh
          geometry={gltf.nodes.Object_116.geometry}
          material={gltf.materials.material_24}
          position={[-49.47, -23.21, 7.5]}
        />
      </T.Group>
      <T.Group
        position={[-188.63, -106.66, 208.66]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, -0.07, 0]}
          scale={[-0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_122.geometry}
              material={gltf.materials.material_25}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_125.geometry}
              material={gltf.materials.material_26}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_128.geometry}
              material={gltf.materials.material_27}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[165.34, -105.36, 194.72]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_134.geometry}
              material={gltf.materials.material_28}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_137.geometry}
              material={gltf.materials.material_29}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_140.geometry}
              material={gltf.materials.material_30}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[165.34, -105.36, 194.72]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_146.geometry}
              material={gltf.materials.material_31}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_149.geometry}
              material={gltf.materials.material_32}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_152.geometry}
              material={gltf.materials.material_33}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[165.34, -105.36, 194.72]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_158.geometry}
              material={gltf.materials.material_34}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_161.geometry}
              material={gltf.materials.material_35}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_164.geometry}
              material={gltf.materials.material_36}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[165.34, -105.36, 194.72]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_170.geometry}
              material={gltf.materials.material_37}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_173.geometry}
              material={gltf.materials.material_38}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_176.geometry}
              material={gltf.materials.material_39}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[193.45, -109.66, 840.05]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_182.geometry}
              material={gltf.materials.material_40}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_185.geometry}
              material={gltf.materials.material_41}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_188.geometry}
              material={gltf.materials.material_42}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[193.45, -109.66, 840.05]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_194.geometry}
              material={gltf.materials.material_43}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_197.geometry}
              material={gltf.materials.material_44}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_200.geometry}
              material={gltf.materials.material_45}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[193.45, -109.66, 840.05]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_206.geometry}
              material={gltf.materials.material_46}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_209.geometry}
              material={gltf.materials.material_47}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_212.geometry}
              material={gltf.materials.material_48}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        position={[193.45, -109.66, 840.05]}
        rotation={[0, 0.09, 0]}
        scale={0.69}
      >
        <T.Group
          rotation={[0, 0.02, 0]}
          scale={[0.9, 1, 1]}
        >
          <T.Group
            rotation={[0, -0.07, 0]}
            scale={0.42}
          >
            <T.Mesh
              geometry={gltf.nodes.Object_218.geometry}
              material={gltf.materials.material_49}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_221.geometry}
              material={gltf.materials.material_50}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
            <T.Mesh
              geometry={gltf.nodes.Object_224.geometry}
              material={gltf.materials.material_51}
              position={[-603.96, 0, 874.91]}
              scale={800.29}
            />
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
