# Cloudflare Pages configuration
name = "cainta-motors"
compatibility_date = "2024-01-01"

[build]
# SvelteKit uses the Cloudflare adapter
command = "npm run build"
cwd = "."
publish = ".svelte-kit/output/client"

# Environment variables for Pages
[env.production.vars]
# Add any production environment variables here

[env.preview.vars]
# Add any preview environment variables here

# Pages configuration
[[pages_build_output_dir]]
# Let SvelteKit handle the build output structure